### ISSUE TITLE
error: unable to create an account

### ISSUE THREAD

**Issue by StevanFreeborn** [Blankeos/resonate-hack#3]
I attempted to create an account and ran into this error on the profile creation page:

```
Failed to Save: Error: ArgumentValidationError: Object is missing the required field `audioBioId`. Consider wrapping the field validator in `v.optional(...)` if this is expected.
```

**Comment by Blankeos** [comment]
Hi @StevanFreeborn ! Damn I can't believe I was running the app for that long without this crucial bug fixed. Just fixed it. It's because I tweaked the mp3 headers for playback purposes on the Safari. 

Thank you so much!
